<?php
$initTypeData = array(
    array(
        "id" => null,
        "name" => "Sales",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Tips",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Other Income",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Equipment",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Rent",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Utility",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Water & Sewer",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Telephone",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Auto Expense",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Bank Charge",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Credit Card Charge",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Office Expenses",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Salary",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Taxes and License Fees",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Insurance",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Advertising & Menu Printing",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Repair & Maintenance",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Legal & Professional Fees",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Garbage Removal",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Postage Expenses",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Other Expenses",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Cost of Goods",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Refund",
        "is_account" => false,
        "is_transaction" => true,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Company",
        "is_account" => true,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Business",
        "is_account" => true,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Employee",
        "is_account" => true,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Main",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => true,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Main",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => true,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Cell",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => true,
        "is_email" => false,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Work",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => true,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Personal",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => true,
        "is_payment" => false,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Cash",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => true,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Credit",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => true,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Check",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => true,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "Gift",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => true,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    ),
    array(
        "id" => null,
        "name" => "ACH",
        "is_account" => false,
        "is_transaction" => false,
        "is_address" => false,
        "is_phone" => false,
        "is_email" => false,
        "is_payment" => true,
        "modified_by" => "SYSTEM",
        "created_by" => "SYSTEM"
    )
);
